job1:
  script:
    - date
    - pwd
    - echo $OAI_USER
    - echo $OAI_PASS
    - echo $OAI_TEST_CASE_GROUP
    - echo $MACHINELIST
    - echo $MACHINELISTGENERIC
    - echo $RESULT_DIR
    - echo $NRUNS_LTE_SOFTMODEM
    - source oaienv
    - cd cmake_targets/autotests/v2
    - python main.py
    - date
  only:
    - triggers
